# Generated by Django 5.0.1 on 2024-01-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_brand_brand_name_brand_name_alter_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
