# Generated by Django 5.0.1 on 2024-01-13 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_day_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['model']},
        ),
    ]
