# Generated by Django 5.0.1 on 2024-01-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='views_by_user',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
