# Generated by Django 5.0.1 on 2024-01-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_car_views_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(default='pendente', editable=False, max_length=50),
        ),
    ]
