# Generated by Django 5.0.1 on 2024-01-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_car_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
        migrations.AddField(
            model_name='car',
            name='allowed',
            field=models.BooleanField(default=False, editable=False, max_length=50),
        ),
    ]
