# Generated by Django 5.0.1 on 2024-01-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_remove_car_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cars', models.IntegerField()),
                ('all_cars_value', models.FloatField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-register_date'],
            },
        ),
    ]
